"""Invalid Tokens table

Revision ID: 20254bdd3faf
Revises: a3c180994d53
Create Date: 2024-01-12 18:38:04.432043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20254bdd3faf'
down_revision = 'a3c180994d53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invalid_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invalid_tokens')
    # ### end Alembic commands ###
