"""sessions and reps

Revision ID: ca62c013851d
Revises: dd0b91e0e31a
Create Date: 2024-01-12 00:01:44.442631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca62c013851d'
down_revision = 'dd0b91e0e31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('climber_id', sa.Integer(), nullable=False),
    sa.Column('crag_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['climber_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['crag_id'], ['crag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_climber_id'), ['climber_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_crag_id'), ['crag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_notes'), ['notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_updated_at'), ['updated_at'], unique=False)

    op.create_table('rep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('climb_id', sa.Integer(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['climb_id'], ['climb.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rep', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rep_climb_id'), ['climb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rep_completed'), ['completed'], unique=False)
        batch_op.create_index(batch_op.f('ix_rep_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_rep_notes'), ['notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_rep_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rep_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(), nullable=False))
        batch_op.drop_index('ix_tag_descr')
        batch_op.create_index(batch_op.f('ix_tag_content'), ['content'], unique=True)
        batch_op.drop_column('descr')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descr', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_index(batch_op.f('ix_tag_content'))
        batch_op.create_index('ix_tag_descr', ['descr'], unique=1)
        batch_op.drop_column('content')

    with op.batch_alter_table('rep', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rep_updated_at'))
        batch_op.drop_index(batch_op.f('ix_rep_session_id'))
        batch_op.drop_index(batch_op.f('ix_rep_notes'))
        batch_op.drop_index(batch_op.f('ix_rep_created_at'))
        batch_op.drop_index(batch_op.f('ix_rep_completed'))
        batch_op.drop_index(batch_op.f('ix_rep_climb_id'))

    op.drop_table('rep')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_updated_at'))
        batch_op.drop_index(batch_op.f('ix_session_notes'))
        batch_op.drop_index(batch_op.f('ix_session_created_at'))
        batch_op.drop_index(batch_op.f('ix_session_crag_id'))
        batch_op.drop_index(batch_op.f('ix_session_climber_id'))

    op.drop_table('session')
    # ### end Alembic commands ###
