"""crag climb tag

Revision ID: d7626bd2b8cb
Revises: c816da6d90e5
Create Date: 2024-01-11 22:26:26.819055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7626bd2b8cb'
down_revision = 'c816da6d90e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crag',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('descr', sa.String(length=200), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('long', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crag_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_crag_descr'), ['descr'], unique=False)
        batch_op.create_index(batch_op.f('ix_crag_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_crag_updated_at'), ['updated_at'], unique=False)

    op.create_table('climb',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('descr', sa.String(length=200), nullable=True),
    sa.Column('crag_id', sa.String(), nullable=False),
    sa.Column('angle', sa.Enum('slab', 'vertical', 'overhang', name='angle_enum'), nullable=False),
    sa.Column('type', sa.Enum('boulder', 'toprope', 'lead', 'trad', name='type_enum'), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('img_url', sa.String(length=80), nullable=True),
    sa.Column('set_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['crag_id'], ['crag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_climb_crag_id'), ['crag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_climb_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_climb_descr'), ['descr'], unique=False)
        batch_op.create_index(batch_op.f('ix_climb_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_climb_set_at'), ['set_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_climb_updated_at'), ['updated_at'], unique=False)

    op.create_table('tag',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('descr', sa.String(length=200), nullable=False),
    sa.Column('climb_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['climb_id'], ['climb.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tag_climb_id'), ['climb_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tag_descr'), ['descr'], unique=True)
        batch_op.create_index(batch_op.f('ix_tag_updated_at'), ['updated_at'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_updated_at'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tag_updated_at'))
        batch_op.drop_index(batch_op.f('ix_tag_descr'))
        batch_op.drop_index(batch_op.f('ix_tag_created_at'))
        batch_op.drop_index(batch_op.f('ix_tag_climb_id'))

    op.drop_table('tag')
    with op.batch_alter_table('climb', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_climb_updated_at'))
        batch_op.drop_index(batch_op.f('ix_climb_set_at'))
        batch_op.drop_index(batch_op.f('ix_climb_name'))
        batch_op.drop_index(batch_op.f('ix_climb_descr'))
        batch_op.drop_index(batch_op.f('ix_climb_created_at'))
        batch_op.drop_index(batch_op.f('ix_climb_crag_id'))

    op.drop_table('climb')
    with op.batch_alter_table('crag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crag_updated_at'))
        batch_op.drop_index(batch_op.f('ix_crag_name'))
        batch_op.drop_index(batch_op.f('ix_crag_descr'))
        batch_op.drop_index(batch_op.f('ix_crag_created_at'))

    op.drop_table('crag')
    # ### end Alembic commands ###
